auto-commits: false
gitignore: false
auto-lint: false
verify-ssl: false

read:
  - ~/dotfiles/aider_config/CONVENTIONS.md
  - ~/dotfiles/aider_config/refactoring_table_references.md
  - ~/dotfiles/aider_config/guide.md
  - ~/dotfiles/aider_config/NewKnowledgeBase.md

dark-mode: true

model: openai/gpt-4o
# deepseek/deepseek-chat or aider --list-models deepseek

openai-api-base: https://api.openai.com/v1

alias:
  - "fast:gpt-4o-mini"
  - "coder:deepseek/deepseek-coder"
# usage: aider --model fast

# Force repo mapping by running aider with `--map-tokens 1024
map-tokens: 0 # disabling scanning repo
# type /tokens
# E.g. $ 0.0050    2,002 system messages - each time we send a prompt, it will cost minimum 0.005

cache-prompts: true
stream: false
# keeps cache warm, hope ping doesn't cost too much money at 5 min intervals.
cache-keepalive-pings: 1

#####################
# History Files:

# Specify chat input history file (default: .aider.input.history
input-history-file: /Users/williamnguyen/.aider.input.history

# Specify chat history file (default: .aider.chat.history.md)
chat-history-file: /Users/williamnguyen/.aider.chat.history.md

